name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  qa:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: shivammathur/setup-php@cf4cade2721270509d5b1c766ab3549210a39a2a # v2.34.1
        with:
          php-version: '8.4'
          extensions: curl, xml
          tools: composer:v2

      - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}
          restore-keys: composer-

      - run: composer config --global github-oauth.github.com ${{ secrets.GITHUB_TOKEN }}

      - run: composer install --no-interaction --prefer-dist

      - name: Coding standards
        run: vendor/bin/phpcs

      - name: PHPStan
        run: vendor/bin/phpstan analyse --no-progress -c phpstan.neon

      - name: Psalm
        run: vendor/bin/psalm --no-progress

      - name: PHPMD
        run: vendor/bin/phpmd src text ./phpmd.xml

      - name: PHPUnit
        run: vendor/bin/phpunit
